In [9]:
import torch

# y = e^(-(5-0.25*(x+5/0.25 - 5))^2/20) from x = -5 to x = 20
# y = e^(-(5-0.25*(i+5/0.25 - 5))^2/20) from x = -5 to x = 20

torch.set_printoptions(precision=10, threshold=100000, sci_mode=False)

def gaussian_connection_probability_matrix(size, c, sigma):
    indices = torch.arange(size, dtype=torch.float32)
    print("Indices:")
    print(indices)
    indices_matrix = indices.unsqueeze(0) - indices.unsqueeze(1)
    print("\nIndices Matrix:")
    print(indices_matrix)
    c_i = c * indices.unsqueeze(1)
    print("C_I")
    print(c_i)
    distances_matrix = torch.abs(indices_matrix - c_i)
    print("\nDistances Matrix:")
    print(distances_matrix)
    gaussian_matrix = torch.exp(-distances_matrix ** 2 / (sigma ** 2))
    print("\nGaussian Matrix:")
    print(gaussian_matrix)
    return gaussian_matrix

# def gaussian_connection_probability_matrix(size, c, sigma):
#     indices = torch.arange(size, dtype=torch.float32)
#     print("Indices:")
#     print(indices)
#     indices_matrix = indices.unsqueeze(0) - indices.unsqueeze(1)
#     print("\nIndices Matrix:")
#     print(indices_matrix)
#     distances_matrix = torch.abs(indices_matrix)
#     print("\nDistances Matrix:")
#     print(distances_matrix)
#     gaussian_matrix = c * torch.exp(-distances_matrix ** 2 / (2 * sigma ** 2))
#     print("\nGaussian Matrix:")
#     print(gaussian_matrix)
#     exit()
#     return gaussian_matrix

def inhibitory_mask_vec(size, percentage_inhibitory):
    num_inhibitory = int(size * percentage_inhibitory / 100)
    mask = torch.zeros(size, dtype=torch.float32)
    mask[:num_inhibitory] = 1
    return mask

# Set the parameters
layer_size = 50
percentage_inhibitory = 50
c = 0.25
sigma = 10

# Create the inhibitory mask vector
inhibitory_mask = inhibitory_mask_vec(layer_size, percentage_inhibitory)
excitatory_mask = (~inhibitory_mask.bool()).float()

# Compute the Gaussian connection probability matrix
gaussian_matrix = gaussian_connection_probability_matrix(layer_size, c, sigma)

# # Sample the excitatory-to-inhibitory mask from the Gaussian matrix
# exc_to_inh_mask = torch.bernoulli(gaussian_matrix)

# # Apply the inhibitory mask to the excitatory-to-inhibitory mask
# exc_to_inh_mask = exc_to_inh_mask * inhibitory_mask.unsqueeze(0)

# # Print the results
# print("Inhibitory Mask:")
# print(inhibitory_mask)
# print("\nExcitatory Mask:")
# print(excitatory_mask)
# print("\nGaussian Connection Probability Matrix:")
# print(gaussian_matrix)
# print("\nExcitatory-to-Inhibitory Mask:")
# print(exc_to_inh_mask)


Indices:
tensor([ 0.,  1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10., 11., 12., 13.,
        14., 15., 16., 17., 18., 19., 20., 21., 22., 23., 24., 25., 26., 27.,
        28., 29., 30., 31., 32., 33., 34., 35., 36., 37., 38., 39., 40., 41.,
        42., 43., 44., 45., 46., 47., 48., 49.])

Indices Matrix:
tensor([[  0.,   1.,   2.,   3.,   4.,   5.,   6.,   7.,   8.,   9.,  10.,  11.,
          12.,  13.,  14.,  15.,  16.,  17.,  18.,  19.,  20.,  21.,  22.,  23.,
          24.,  25.,  26.,  27.,  28.,  29.,  30.,  31.,  32.,  33.,  34.,  35.,
          36.,  37.,  38.,  39.,  40.,  41.,  42.,  43.,  44.,  45.,  46.,  47.,
          48.,  49.],
        [ -1.,   0.,   1.,   2.,   3.,   4.,   5.,   6.,   7.,   8.,   9.,  10.,
          11.,  12.,  13.,  14.,  15.,  16.,  17.,  18.,  19.,  20.,  21.,  22.,
          23.,  24.,  25.,  26.,  27.,  28.,  29.,  30.,  31.,  32.,  33.,  34.,
          35.,  36.,  37.,  38.,  39.,  40.,  41.,  42.,  43.,  44.,  45.,  46.,
          47.,  48.],

In [14]:
import torch

# y = e^(-(5-0.25*(x+5/0.25 - 5))^2/20) from x = -5 to x = 20
# y = e^(-(5-0.25*(i+5/0.25 - 5))^2/20) from x = -5 to x = 20

torch.set_printoptions(precision=10, threshold=100000, sci_mode=False)

def gaussian_connection_probability_matrix(size_i, size_j, c = 0.25, sigma_squared = 20):
    indices_i = torch.arange(size_i, dtype=torch.float32).unsqueeze(1).expand(-1, size_j)
    indices_j = torch.arange(size_j, dtype=torch.float32).unsqueeze(0).expand(size_i, -1)

    pre_exp = -1 * (indices_j - c * (indices_i + indices_j/c - indices_j)) ** 2 / sigma_squared
    return torch.exp(pre_exp)

def inhibitory_mask_vec(size, percentage_inhibitory):
    num_inhibitory = int(size * percentage_inhibitory / 100)
    mask = torch.zeros(size, dtype=torch.float32)
    mask[:num_inhibitory] = 1
    return mask

# Set the parameters
layer_size_i = 50
layer_size_j = 50
percentage_inhibitory = 50

# Create the inhibitory mask vector
inhibitory_mask = inhibitory_mask_vec(layer_size, percentage_inhibitory)
excitatory_mask = (~inhibitory_mask.bool()).float()

# Compute the Gaussian connection probability matrix
gaussian_matrix = gaussian_connection_probability_matrix(layer_size_i, layer_size_j)
print(gaussian_matrix.shape)

# # Sample the excitatory-to-inhibitory mask from the Gaussian matrix
exc_to_inh_mask = torch.bernoulli(gaussian_matrix)
print(exc_to_inh_mask)

# # Apply the inhibitory mask to the excitatory-to-inhibitory mask
# exc_to_inh_mask = exc_to_inh_mask * inhibitory_mask.unsqueeze(0)

# # Print the results
# print("Inhibitory Mask:")
# print(inhibitory_mask)
# print("\nExcitatory Mask:")
# print(excitatory_mask)
# print("\nGaussian Connection Probability Matrix:")
# print(gaussian_matrix)
# print("\nExcitatory-to-Inhibitory Mask:")
# print(exc_to_inh_mask)


tensor([[1., 1., 1., 1., 1., 1., 1., 1., 1., 0., 1., 1., 1., 0., 0., 0., 0., 1.,
         1., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
         0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
        [1., 1., 1., 1., 1., 1., 1., 1., 1., 0., 1., 1., 1., 0., 0., 1., 1., 1.,
         0., 0., 1., 0., 1., 0., 0., 0., 0., 1., 0., 0., 0., 1., 0., 0., 0., 0.,
         0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
        [1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 0., 1., 1., 0., 0., 1., 1., 1.,
         1., 1., 1., 0., 0., 1., 0., 0., 0., 0., 0., 0., 1., 1., 0., 0., 0., 0.,
         0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
        [1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 0., 1., 1., 1., 1., 1., 0.,
         0., 0., 0., 0., 1., 0., 0., 1., 0., 1., 0., 0., 0., 0., 1., 0., 0., 0.,
         0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
        [1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 0., 1., 1., 0., 1., 1.,
       